name: MLCommons RNN Speech Recognition Training Reference Benchmark
author: MLCommons Best Practices Working Group

tasks:
  # Download LibriSpeech dataset
  download_data:
    parameters:
      # Directory for uncompressed datasets. Total size is ~ 65G.
      - {name: data_dir,  type: directory, io: output}
    tasks:
      download_data: {data_dir: $WORKSPACE/data}
  # Preprocess dataset
  preprocess_data:
    parameters:
      # Same directory location where dataset was downloaded
      # When finished total size is ~ 112G
      - {name: data_dir,  type: directory, io: output}
    tasks:
      preprocess_data: {data_dir: $WORKSPACE/data}
  # Train RNN speech recognition model
  train:
    parameters:
      # see Download::data_dir
      - {name: data_dir,            type: directory, io: input}
      # Model output folder
      - {name: output_dir,            type: directory, io: output}
      # Yaml file with training parameters.
      - {name: parameters_file,     type: file,      io: input}
    tasks:
      train:
        data_dir: $WORKSPACE/data/LibriSpeech
        output_dir: $WORKSPACE/output
        parameters_file: $WORKSPACE/parameters.yaml
